// Shopify Admin API helpers for triggering shipping notification emails.

const API_VERSION = () => process.env.API_VERSION || '2026-01';

// Couriers with "Checking AWB" support on the RajaOngkir proxy
// (rajaongkir-proxy/api/tracking.js). Slug must match both the proxy's
// courier code and the <option value> in the tracking page's select.
// phoneDigits mirrors the proxy's COURIER_PHONE_DIGITS (jne: 5).
// J&T does not require phone verification on the RajaOngkir API.
// No AWB checking (excluded): ide, sentral, rex.
const SUPPORTED_COURIERS = [
  { slug: 'jne', phoneDigits: 5, matches: ['jne'] },
  { slug: 'jnt', phoneDigits: 0, matches: ['jnt', 'jtexpress', 'jtekspres', 'jtez', 'jteco', 'jtsuper', 'jandt'] },
  { slug: 'sicepat', phoneDigits: 0, matches: ['sicepat'] },
  { slug: 'sap', phoneDigits: 0, matches: ['sapexpress', 'sapekspres'] },
  { slug: 'ninja', phoneDigits: 0, matches: ['ninja'] },
  { slug: 'tiki', phoneDigits: 0, matches: ['tiki'] },
  { slug: 'wahana', phoneDigits: 0, matches: ['wahana'] },
  { slug: 'pos', phoneDigits: 0, matches: ['posindonesia', 'posind', 'posaja'] },
  { slug: 'lion', phoneDigits: 0, matches: ['lion'] },
];

// Couriers RajaOngkir can't track (no AWB checking) — fall back to the
// courier's own official tracking site. {awb} is replaced with the
// tracking number; templates without {awb} just open the tracking page.
const FALLBACK_COURIERS = [
  { slug: 'ide', matches: ['idexpress', 'idekspres'], urlTemplate: 'https://idexpress.com/lacak-paket?waybillNo={awb}' },
  { slug: 'rex', matches: ['royalexpress', 'rexkiriman'], urlTemplate: 'https://rex.co.id/id/tracking/?airwaybill={awb}' },
  { slug: 'spx', matches: ['shopeexpress', 'shopeeexpress', 'shopeexpres'], urlTemplate: 'https://spx.co.id/track?{awb}' },
  { slug: 'grab', matches: ['grabexpress', 'grabinstant', 'grabsameday'], urlTemplate: 'https://express.grab.com/track/orders?ids={awb}' },
  { slug: 'anteraja', matches: ['anteraja'], urlTemplate: 'https://anteraja.id/tracking' },
  { slug: 'sentral', matches: ['sentralcargo'], urlTemplate: 'https://sentralcargo.co.id/cekresi' },
  { slug: 'paxel', matches: ['paxel'], urlTemplate: 'https://paxel.co/id/lacak-pengiriman' },
  { slug: 'indah', matches: ['indahcargo', 'indahlogistik', 'indahonline'], urlTemplate: 'https://indahonline.com' },
  { slug: 'dakota', matches: ['dakotacargo', 'dakota'], urlTemplate: 'https://dakotacargo.co.id' },
  { slug: 'rpx', matches: ['rpxexpress', 'rpxholding', 'rpx'], urlTemplate: 'https://www.rpx.co.id' },
  { slug: 'kgx', matches: ['kgxpress', 'kgexpress'], urlTemplate: 'https://kgx.co.id' },
  { slug: 'pahala', matches: ['pahalaexpress', 'pahalakencana', 'pahala'], urlTemplate: 'https://www.pahalaexpress.co.id' },
  { slug: 'pandu', matches: ['pandulogistics', 'pandu'], urlTemplate: 'https://www.pandulogistics.com' },
  { slug: 'first', matches: ['firstlogistics'], urlTemplate: 'https://www.firstlogistics.co.id' },
];

// Instant/on-demand couriers (GoSend, Lalamove, Borzo, Deliveree, …) have
// no public AWB page — their tracking links are per-order dynamic URLs
// generated by the shipping app. For those (and any other unknown courier)
// we keep the app's tracking_url as-is instead of overwriting it.

// Recognizable AWB prefixes — used when the carrier is "Other"/empty
// (manual fulfillments often leave the carrier dropdown on "Other").
// Only high-confidence patterns; ambiguous all-numeric AWBs (JNE,
// Anteraja, SiCepat, …) are resolved via the order's shipping line instead.
const AWB_PATTERNS = [
  { slug: 'tiki', pattern: /^TIKI/i },            // TIKIBTS100000111380
  { slug: 'ide', pattern: /^IDE\d/i },            // IDE7000910703355
  { slug: 'spx', pattern: /^SPX/i },              // SPXID04...
  { slug: 'jnt', pattern: /^(JP|JT|JD|JO)\d{8,}$/i }, // JP1234567890, JO0325596223 (EZ)
  { slug: 'paxel', pattern: /^EM\./i },           // EM.L7S6JYQ48W-...
  { slug: 'lion', pattern: /^\d{2}LP\d/i },       // 99LP1783206910626
  { slug: 'sicepat', pattern: /^00\d{10}$/ },     // 005000071858 (12 digits, starts 00)
];

// Resolve courier from carrier name first, then from the AWB pattern.
// Returns { courier, fallback } (either may be null). Synchronous on
// purpose so the webhook loop guard can reuse the exact same logic.
function detectCourierSync(trackingCompany, trackingNumber) {
  let courier = matchCourier(SUPPORTED_COURIERS, trackingCompany);
  let fallback = courier ? null : matchCourier(FALLBACK_COURIERS, trackingCompany);
  if (!courier && !fallback && trackingNumber) {
    const hit = AWB_PATTERNS.find((p) => p.pattern.test(String(trackingNumber).trim()));
    if (hit) {
      courier = SUPPORTED_COURIERS.find((c) => c.slug === hit.slug) || null;
      fallback = FALLBACK_COURIERS.find((c) => c.slug === hit.slug) || null;
    }
  }
  return { courier, fallback };
}

// True if the URL points at any official-site fallback we could have set —
// used by the webhook loop guard to avoid re-notifying on our own updates.
function isFallbackUrl(url) {
  if (typeof url !== 'string') return false;
  return FALLBACK_COURIERS.some((c) => url.startsWith(c.urlTemplate.split('?')[0]));
}

// Match a tracking_company against a courier list. Exact slug match is
// checked first so short codes like "SAP"/"POS"/"IDE" work without
// risking substring false positives (e.g. "ide" inside "rider").
function matchCourier(list, trackingCompany) {
  if (!trackingCompany) return null;
  const normalized = trackingCompany.toLowerCase().replace(/[^a-z0-9]/g, '');
  return (
    list.find((c) => normalized === c.slug) ||
    list.find((c) => c.matches.some((m) => normalized.includes(m))) ||
    null
  );
}

// Map Shopify's tracking_company (e.g. "JNE REGULER", "J&T Express",
// "Tiki Indonesia - Economy") to a RajaOngkir-supported courier.
function resolveCourier(trackingCompany) {
  return matchCourier(SUPPORTED_COURIERS, trackingCompany);
}

// Build the official-site tracking URL from a fallback entry.
function buildFallbackUrl(entry, trackingNumber) {
  if (!entry) return null;
  if (entry.urlTemplate.includes('{awb}') && !trackingNumber) {
    return entry.urlTemplate.replace(/[?&][^?&]*\{awb\}.*$/, '').replace('{awb}', '');
  }
  return entry.urlTemplate.replace('{awb}', encodeURIComponent(trackingNumber || ''));
}

// Official-site tracking URL for couriers RajaOngkir doesn't cover
// (carrier name or AWB pattern). Returns null if no fallback matches.
function fallbackTrackingUrl(trackingCompany, trackingNumber) {
  const { fallback } = detectCourierSync(trackingCompany, trackingNumber);
  return buildFallbackUrl(fallback, trackingNumber);
}

// Base tracking page URL. A store's SHOPIFY_STORES entry can set "url"
// (e.g. a custom domain like https://wearemandalas.com/pages/tracking-page);
// otherwise SHOPIFY_URL is used, with ${SHOP} replaced by the shop domain.
function trackingPageBase(shopDomain) {
  const entry = parseStores()[(shopDomain || '').toLowerCase()];
  if (entry?.url) return entry.url;
  const template = process.env.SHOPIFY_URL || `https://${shopDomain}/pages/tracking-page`;
  return template.replace('${SHOP}', shopDomain).replace('#{SHOP}', shopDomain);
}

// Build the customer-facing URL. The tracking page auto-runs when
// tracking_number is present, using ?courier=<slug> and, for JNE,
// ?phone=<last 5 digits> to pre-fill the OTP boxes.
// If the courier is not supported by the page, return the bare page URL
// (auto-run with the wrong courier would just show an API error).
function buildTrackingPageUrl(shopDomain, { trackingNumber, courier, phoneLastDigits } = {}) {
  const base = trackingPageBase(shopDomain);
  if (!trackingNumber || !courier) return base;

  const params = new URLSearchParams({ tracking_number: trackingNumber, courier: courier.slug });
  if (courier.phoneDigits > 0 && phoneLastDigits) {
    params.set('phone', phoneLastDigits);
  }
  return `${base}${base.includes('?') ? '&' : '?'}${params.toString()}`;
}

// Per-store credentials for multitenant setups. SHOPIFY_STORES is a JSON
// object keyed by shop domain:
//   SHOPIFY_STORES={"happytap.myshopify.com":{"token":"shpca_...","webhookSecret":"..."},
//                   "hafidz-dev.myshopify.com":{"token":"shpat_...","webhookSecret":"..."}}
// Falls back to SHOPIFY_ACCESS_TOKEN / SHOPIFY_WEBHOOK_SECRET when a shop
// has no entry (single-store backwards compatibility).
function parseStores() {
  try {
    return JSON.parse(process.env.SHOPIFY_STORES || '{}');
  } catch (err) {
    console.error('❌ SHOPIFY_STORES is not valid JSON:', err.message);
    return {};
  }
}

// Alternative multitenant format: comma-separated lists aligned by position
// with SHOP, e.g.
//   SHOP=happytap.myshopify.com,hafidz-dev.myshopify.com
//   SHOPIFY_ACCESS_TOKEN=shpca_aaa,shpca_bbb
//   SHOPIFY_WEBHOOK_SECRET=secret-for-happytap,secret-for-hafidz-dev
// A single value (no comma) keeps working for single-store setups.
function envListConfig(shopDomain) {
  const splitList = (v) => (v || '').split(',').map((s) => s.trim()).filter(Boolean);
  const shops = splitList(process.env.SHOP).map((s) => s.toLowerCase());
  const tokens = splitList(process.env.SHOPIFY_ACCESS_TOKEN);
  const secrets = splitList(process.env.SHOPIFY_WEBHOOK_SECRET);
  const idx = shops.indexOf((shopDomain || '').toLowerCase());
  return {
    token: (idx >= 0 && tokens[idx]) || tokens[0],
    webhookSecret: (idx >= 0 && secrets[idx]) || secrets[0],
  };
}

function getShopConfig(shopDomain) {
  const entry = parseStores()[(shopDomain || '').toLowerCase()];
  const listCfg = envListConfig(shopDomain);
  return {
    token: entry?.token || listCfg.token,
    webhookSecret: entry?.webhookSecret || listCfg.webhookSecret,
  };
}

// Check the shop that sent the webhook is one we manage: listed in
// SHOPIFY_STORES or in SHOP (comma separated).
function isKnownShop(shopDomain) {
  const domain = (shopDomain || '').toLowerCase();
  const stores = Object.keys(parseStores()).map((s) => s.toLowerCase());
  const shops = (process.env.SHOP || '')
    .split(',')
    .map((s) => s.trim().toLowerCase())
    .filter(Boolean);
  const known = [...stores, ...shops];
  if (known.length === 0) return true; // no allowlist configured
  return known.includes(domain);
}

function lastDigits(phone, count) {
  if (!phone) return null;
  const digits = String(phone).replace(/\D/g, '');
  return digits.length >= count ? digits.slice(-count) : null;
}

// Fetch the recipient's phone and the shipping method title from the
// order. The shipping line title (e.g. "JNE - Non Instan") is used to
// detect the courier when the fulfillment's carrier is "Other"/empty.
// Requires read_orders scope.
async function fetchOrderInfo(shopDomain, orderId) {
  const { token } = getShopConfig(shopDomain);
  const url = `https://${shopDomain}/admin/api/${API_VERSION()}/orders/${orderId}.json?fields=phone,shipping_address,customer,shipping_lines`;
  const res = await fetch(url, { headers: { 'X-Shopify-Access-Token': token } });
  if (!res.ok) {
    console.warn(`   ⚠️  Could not fetch order ${orderId} (${res.status})`);
    return {};
  }
  const { order } = await res.json();
  const line = order?.shipping_lines?.[0];
  return {
    phone:
      order?.shipping_address?.phone ||
      order?.phone ||
      order?.customer?.phone ||
      order?.customer?.default_address?.phone ||
      null,
    shippingTitle: line ? `${line.title || ''} ${line.code || ''} ${line.source || ''}` : null,
  };
}

// ---------------------------------------------------------------------------
// "Already notified" marker, stored on the order as a metafield so it
// survives serverless restarts (in-memory state does not on Vercel).
// namespace east_rose, key awb_<fulfillmentId>, value = tracking number
// (or the app's tracking URL for URL-only couriers like GoSend).
// Reading needs read_orders, writing needs write_orders — on 403 we log a
// hint and the webhook falls back to in-memory dedup only.
// ---------------------------------------------------------------------------
const METAFIELD_NAMESPACE = 'east_rose';

async function getNotifiedTracking(shopDomain, orderId, fulfillmentId) {
  const none = { value: null, metafieldId: null };
  const { token } = getShopConfig(shopDomain);
  if (!token || !orderId || !fulfillmentId) return none;
  try {
    const key = `awb_${fulfillmentId}`;
    const url = `https://${shopDomain}/admin/api/${API_VERSION()}/orders/${orderId}/metafields.json?namespace=${METAFIELD_NAMESPACE}&key=${key}`;
    const res = await fetch(url, { headers: { 'X-Shopify-Access-Token': token } });
    if (!res.ok) {
      const hint = res.status === 403 ? ' — grant read_orders/write_orders to dedup across restarts' : '';
      console.warn(`   ⚠️  Could not read notified-tracking metafield (${res.status})${hint}`);
      return none;
    }
    const { metafields } = await res.json();
    const mf = metafields?.[0];
    return { value: mf?.value != null ? String(mf.value) : null, metafieldId: mf?.id || null };
  } catch (err) {
    console.warn(`   ⚠️  Could not read notified-tracking metafield: ${err.message}`);
    return none;
  }
}

async function markNotifiedTracking(shopDomain, orderId, fulfillmentId, value, metafieldId) {
  const { token } = getShopConfig(shopDomain);
  if (!token || !orderId || !fulfillmentId || !value) return;
  try {
    const base = `https://${shopDomain}/admin/api/${API_VERSION()}/orders/${orderId}/metafields`;
    const url = metafieldId ? `${base}/${metafieldId}.json` : `${base}.json`;
    const metafield = metafieldId
      ? { id: metafieldId, value: String(value), type: 'single_line_text_field' }
      : {
          namespace: METAFIELD_NAMESPACE,
          key: `awb_${fulfillmentId}`,
          type: 'single_line_text_field',
          value: String(value),
        };
    const res = await fetch(url, {
      method: metafieldId ? 'PUT' : 'POST',
      headers: { 'X-Shopify-Access-Token': token, 'Content-Type': 'application/json' },
      body: JSON.stringify({ metafield }),
    });
    if (!res.ok) {
      const hint = res.status === 403 ? ' — grant write_orders to dedup across restarts' : '';
      console.warn(`   ⚠️  Could not save notified-tracking metafield (${res.status})${hint}`);
    }
  } catch (err) {
    console.warn(`   ⚠️  Could not save notified-tracking metafield: ${err.message}`);
  }
}

/**
 * Update a fulfillment's tracking info and ask Shopify to email the customer.
 * Shopify sends its native "Shipping confirmation" (or "Shipping update")
 * email, which includes the tracking URL we set here.
 */
async function notifyCustomerShipping({
  shopDomain,
  fulfillmentId,
  orderId,
  trackingNumber,
  trackingCompany,
  destinationPhone,
  existingTrackingUrl,
}) {
  const { token } = getShopConfig(shopDomain);
  if (!token) throw new Error(`No access token configured for ${shopDomain} (SHOPIFY_STORES or SHOPIFY_ACCESS_TOKEN)`);

  // Fetch the order lazily, at most once (phone + shipping method title)
  let orderInfoCache = null;
  const getOrderInfo = async () => {
    if (!orderInfoCache) orderInfoCache = orderId ? await fetchOrderInfo(shopDomain, orderId) : {};
    return orderInfoCache;
  };

  // Detect the courier from, in order of confidence:
  //  1. the fulfillment's carrier name (what was actually used)
  //  2. the order's shipping method title (merchant-chosen, stable —
  //     covers manual fulfillments where the carrier is left on "Other")
  //  3. the AWB prefix pattern, as a last resort (AWB formats vary,
  //     especially aggregator waybills like KAJ.../JO...)
  let courier = matchCourier(SUPPORTED_COURIERS, trackingCompany);
  let fallback = courier ? null : matchCourier(FALLBACK_COURIERS, trackingCompany);

  if (!courier && !fallback && orderId) {
    const { shippingTitle } = await getOrderInfo();
    if (shippingTitle) {
      courier = matchCourier(SUPPORTED_COURIERS, shippingTitle);
      fallback = courier ? null : matchCourier(FALLBACK_COURIERS, shippingTitle);
      if (courier || fallback) {
        console.log(`   🔎 Courier detected from order shipping method "${shippingTitle.trim()}"`);
      }
    }
  }

  if (!courier && !fallback && trackingNumber) {
    const hit = AWB_PATTERNS.find((p) => p.pattern.test(String(trackingNumber).trim()));
    if (hit) {
      courier = SUPPORTED_COURIERS.find((c) => c.slug === hit.slug) || null;
      fallback = FALLBACK_COURIERS.find((c) => c.slug === hit.slug) || null;
      if (courier || fallback) {
        console.log(`   🔎 Courier detected from AWB pattern (${hit.slug})`);
      }
    }
  }

  // JNE tracking needs the last digits of the recipient's phone number
  let phoneLastDigits = null;
  if (courier && courier.phoneDigits > 0) {
    let phone = destinationPhone;
    if (!phone) phone = (await getOrderInfo()).phone;
    phoneLastDigits = lastDigits(phone, courier.phoneDigits);
    if (!phoneLastDigits) {
      console.warn(`   ⚠️  No recipient phone found for ${courier.slug.toUpperCase()} — customer will be asked for it on the page`);
    }
  }

  let trackingPageUrl;
  if (courier) {
    trackingPageUrl = buildTrackingPageUrl(shopDomain, { trackingNumber, courier, phoneLastDigits });
  } else if (fallback) {
    // RajaOngkir can't track this courier — link to its official site
    console.log(`   ℹ️  Courier "${fallback.slug}" not covered by RajaOngkir — linking to official site`);
    trackingPageUrl = buildFallbackUrl(fallback, trackingNumber);
  } else if (existingTrackingUrl) {
    // Unknown courier — keep the shipping app's own tracking link
    // (e.g. GoSend/Grab live-tracking URLs)
    console.log(`   ℹ️  Courier "${trackingCompany}" unknown — keeping the app's own tracking link`);
    trackingPageUrl = existingTrackingUrl;
  } else {
    console.log(`   ℹ️  Courier "${trackingCompany}" unknown — linking to plain tracking page`);
    trackingPageUrl = trackingPageBase(shopDomain);
  }

  const tracking_info = { url: trackingPageUrl };
  if (trackingNumber) tracking_info.number = trackingNumber;
  if (trackingCompany) tracking_info.company = trackingCompany;

  const url = `https://${shopDomain}/admin/api/${API_VERSION()}/fulfillments/${fulfillmentId}/update_tracking.json`;
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'X-Shopify-Access-Token': token,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      fulfillment: {
        notify_customer: true,
        tracking_info,
      },
    }),
  });

  const body = await res.text();
  if (!res.ok) {
    throw new Error(`Shopify update_tracking failed (${res.status}): ${body}`);
  }

  return { trackingPageUrl, courier: courier?.slug || null, response: JSON.parse(body) };
}

module.exports = {
  notifyCustomerShipping,
  getNotifiedTracking,
  markNotifiedTracking,
  buildTrackingPageUrl,
  trackingPageBase,
  resolveCourier,
  fallbackTrackingUrl,
  detectCourierSync,
  isFallbackUrl,
  isKnownShop,
  getShopConfig,
};
