// Shopify Admin API helpers for triggering shipping notification emails.

const API_VERSION = () => process.env.API_VERSION || '2026-01';

// Couriers with "Checking AWB" support on the RajaOngkir proxy
// (rajaongkir-proxy/api/tracking.js). Slug must match both the proxy's
// courier code and the <option value> in the tracking page's select.
// phoneDigits mirrors the proxy's COURIER_PHONE_DIGITS (jne: 5, jnt: 4).
// No AWB checking (excluded): ide, sentral, rex.
const SUPPORTED_COURIERS = [
  { slug: 'jne', phoneDigits: 5, matches: ['jne'] },
  { slug: 'jnt', phoneDigits: 4, matches: ['jnt', 'jtexpress', 'jtekspres'] },
  { slug: 'sicepat', phoneDigits: 0, matches: ['sicepat'] },
  { slug: 'sap', phoneDigits: 0, matches: ['sapexpress', 'sapekspres'] },
  { slug: 'ninja', phoneDigits: 0, matches: ['ninja'] },
  { slug: 'tiki', phoneDigits: 0, matches: ['tiki'] },
  { slug: 'wahana', phoneDigits: 0, matches: ['wahana'] },
  { slug: 'pos', phoneDigits: 0, matches: ['posindonesia', 'posind', 'posaja'] },
  { slug: 'lion', phoneDigits: 0, matches: ['lion'] },
];

// Couriers RajaOngkir can't track (no AWB checking) — fall back to the
// courier's own official tracking site. {awb} is replaced with the
// tracking number; templates without {awb} just open the tracking page.
const FALLBACK_COURIERS = [
  { slug: 'ide', matches: ['idexpress', 'idekspres'], urlTemplate: 'https://idexpress.com/lacak-paket?waybillNo={awb}' },
  { slug: 'rex', matches: ['royalexpress', 'rexkiriman'], urlTemplate: 'https://rex.co.id/id/tracking/?airwaybill={awb}' },
  { slug: 'spx', matches: ['shopeexpress', 'shopeeexpress', 'shopeexpres'], urlTemplate: 'https://spx.co.id/track?{awb}' },
  { slug: 'grab', matches: ['grabexpress', 'grabinstant', 'grabsameday'], urlTemplate: 'https://express.grab.com/track/orders?ids={awb}' },
  { slug: 'anteraja', matches: ['anteraja'], urlTemplate: 'https://anteraja.id/tracking' },
  { slug: 'sentral', matches: ['sentralcargo'], urlTemplate: 'https://sentralcargo.co.id/cekresi' },
  { slug: 'paxel', matches: ['paxel'], urlTemplate: 'https://paxel.co/id/lacak-pengiriman' },
  { slug: 'indah', matches: ['indahcargo', 'indahlogistik', 'indahonline'], urlTemplate: 'https://indahonline.com' },
  { slug: 'dakota', matches: ['dakotacargo', 'dakota'], urlTemplate: 'https://dakotacargo.co.id' },
  { slug: 'rpx', matches: ['rpxexpress', 'rpxholding', 'rpx'], urlTemplate: 'https://www.rpx.co.id' },
  { slug: 'kgx', matches: ['kgxpress', 'kgexpress'], urlTemplate: 'https://kgx.co.id' },
  { slug: 'pahala', matches: ['pahalaexpress', 'pahalakencana', 'pahala'], urlTemplate: 'https://www.pahalaexpress.co.id' },
  { slug: 'pandu', matches: ['pandulogistics', 'pandu'], urlTemplate: 'https://www.pandulogistics.com' },
  { slug: 'first', matches: ['firstlogistics'], urlTemplate: 'https://www.firstlogistics.co.id' },
];

// Instant/on-demand couriers (GoSend, Lalamove, Borzo, Deliveree, …) have
// no public AWB page — their tracking links are per-order dynamic URLs
// generated by the shipping app. For those (and any other unknown courier)
// we keep the app's tracking_url as-is instead of overwriting it.

// Match a tracking_company against a courier list. Exact slug match is
// checked first so short codes like "SAP"/"POS"/"IDE" work without
// risking substring false positives (e.g. "ide" inside "rider").
function matchCourier(list, trackingCompany) {
  if (!trackingCompany) return null;
  const normalized = trackingCompany.toLowerCase().replace(/[^a-z0-9]/g, '');
  return (
    list.find((c) => normalized === c.slug) ||
    list.find((c) => c.matches.some((m) => normalized.includes(m))) ||
    null
  );
}

// Map Shopify's tracking_company (e.g. "JNE REGULER", "J&T Express",
// "Tiki Indonesia - Economy") to a RajaOngkir-supported courier.
function resolveCourier(trackingCompany) {
  return matchCourier(SUPPORTED_COURIERS, trackingCompany);
}

// Official-site tracking URL for couriers RajaOngkir doesn't cover.
// Returns null if the courier has no fallback entry.
function fallbackTrackingUrl(trackingCompany, trackingNumber) {
  const fallback = matchCourier(FALLBACK_COURIERS, trackingCompany);
  if (!fallback) return null;
  if (fallback.urlTemplate.includes('{awb}') && !trackingNumber) {
    return fallback.urlTemplate.replace(/[?&][^?&]*\{awb\}.*$/, '').replace('{awb}', '');
  }
  return fallback.urlTemplate.replace('{awb}', encodeURIComponent(trackingNumber || ''));
}

// Base tracking page URL from env. Supports ${SHOP} placeholder so it
// works for multiple shops, e.g. SHOPIFY_URL=https://${SHOP}/pages/tracking-page
function trackingPageBase(shopDomain) {
  const template = process.env.SHOPIFY_URL || `https://${shopDomain}/pages/tracking-page`;
  return template.replace('${SHOP}', shopDomain).replace('#{SHOP}', shopDomain);
}

// Build the customer-facing URL. The tracking page auto-runs when
// tracking_number is present, using ?courier=<slug> and, for JNE,
// ?phone=<last 5 digits> to pre-fill the OTP boxes.
// If the courier is not supported by the page, return the bare page URL
// (auto-run with the wrong courier would just show an API error).
function buildTrackingPageUrl(shopDomain, { trackingNumber, courier, phoneLastDigits } = {}) {
  const base = trackingPageBase(shopDomain);
  if (!trackingNumber || !courier) return base;

  const params = new URLSearchParams({ tracking_number: trackingNumber, courier: courier.slug });
  if (courier.phoneDigits > 0 && phoneLastDigits) {
    params.set('phone', phoneLastDigits);
  }
  return `${base}${base.includes('?') ? '&' : '?'}${params.toString()}`;
}

// Check the shop that sent the webhook is one we manage (SHOP can be comma separated).
function isKnownShop(shopDomain) {
  const shops = (process.env.SHOP || '')
    .split(',')
    .map((s) => s.trim().toLowerCase())
    .filter(Boolean);
  if (shops.length === 0) return true; // no allowlist configured
  return shops.includes((shopDomain || '').toLowerCase());
}

function lastDigits(phone, count) {
  if (!phone) return null;
  const digits = String(phone).replace(/\D/g, '');
  return digits.length >= count ? digits.slice(-count) : null;
}

// Fallback: fetch the recipient's phone from the order when the
// fulfillment's destination has none. Requires read_orders scope.
async function fetchOrderPhone(shopDomain, orderId) {
  const token = process.env.SHOPIFY_ACCESS_TOKEN;
  const url = `https://${shopDomain}/admin/api/${API_VERSION()}/orders/${orderId}.json?fields=phone,shipping_address,customer`;
  const res = await fetch(url, { headers: { 'X-Shopify-Access-Token': token } });
  if (!res.ok) {
    console.warn(`   ⚠️  Could not fetch order ${orderId} for phone lookup (${res.status})`);
    return null;
  }
  const { order } = await res.json();
  return (
    order?.shipping_address?.phone ||
    order?.phone ||
    order?.customer?.phone ||
    order?.customer?.default_address?.phone ||
    null
  );
}

/**
 * Update a fulfillment's tracking info and ask Shopify to email the customer.
 * Shopify sends its native "Shipping confirmation" (or "Shipping update")
 * email, which includes the tracking URL we set here.
 */
async function notifyCustomerShipping({
  shopDomain,
  fulfillmentId,
  orderId,
  trackingNumber,
  trackingCompany,
  destinationPhone,
  existingTrackingUrl,
}) {
  const token = process.env.SHOPIFY_ACCESS_TOKEN;
  if (!token) throw new Error('SHOPIFY_ACCESS_TOKEN is not set');

  const courier = resolveCourier(trackingCompany);

  // JNE/J&T tracking needs the last digits of the recipient's phone number
  let phoneLastDigits = null;
  if (courier && courier.phoneDigits > 0) {
    let phone = destinationPhone;
    if (!phone && orderId) phone = await fetchOrderPhone(shopDomain, orderId);
    phoneLastDigits = lastDigits(phone, courier.phoneDigits);
    if (!phoneLastDigits) {
      console.warn(`   ⚠️  No recipient phone found for ${courier.slug.toUpperCase()} — customer will be asked for it on the page`);
    }
  }

  let trackingPageUrl;
  if (courier) {
    trackingPageUrl = buildTrackingPageUrl(shopDomain, { trackingNumber, courier, phoneLastDigits });
  } else {
    // RajaOngkir can't track this courier — link to its official site if
    // we know it. Otherwise keep the shipping app's own tracking link
    // (e.g. GoSend/Grab live-tracking URLs), or the bare tracking page
    // as the last resort.
    const officialUrl = fallbackTrackingUrl(trackingCompany, trackingNumber);
    if (officialUrl) {
      console.log(`   ℹ️  Courier "${trackingCompany}" not covered by RajaOngkir — linking to official site`);
      trackingPageUrl = officialUrl;
    } else if (existingTrackingUrl) {
      console.log(`   ℹ️  Courier "${trackingCompany}" unknown — keeping the app's own tracking link`);
      trackingPageUrl = existingTrackingUrl;
    } else {
      console.log(`   ℹ️  Courier "${trackingCompany}" unknown — linking to plain tracking page`);
      trackingPageUrl = trackingPageBase(shopDomain);
    }
  }

  const tracking_info = { url: trackingPageUrl };
  if (trackingNumber) tracking_info.number = trackingNumber;
  if (trackingCompany) tracking_info.company = trackingCompany;

  const url = `https://${shopDomain}/admin/api/${API_VERSION()}/fulfillments/${fulfillmentId}/update_tracking.json`;
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      'X-Shopify-Access-Token': token,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      fulfillment: {
        notify_customer: true,
        tracking_info,
      },
    }),
  });

  const body = await res.text();
  if (!res.ok) {
    throw new Error(`Shopify update_tracking failed (${res.status}): ${body}`);
  }

  return { trackingPageUrl, courier: courier?.slug || null, response: JSON.parse(body) };
}

module.exports = {
  notifyCustomerShipping,
  buildTrackingPageUrl,
  trackingPageBase,
  resolveCourier,
  fallbackTrackingUrl,
  isKnownShop,
};
